Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2018-10, with the labels that each got.

#9 Add: typed value & schema validation
  fieldpath/element_test.go
  fieldpath/set.go
  fieldpath/set_test.go
  typed/typed.go
  typed/validate.go
  typed/validate_test.go
  value/unstructured.go
  value/unstructured_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#10 Add SetFromValue (sans schema)
  fieldpath/element.go
  fieldpath/fromvalue.go
  fieldpath/fromvalue_test.go
  fieldpath/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#11 add typed version of fieldset
  schema/elements.go
  typed/toset_test.go
  typed/typed.go
  typed/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#13 Validation fixes
  schema/elements.go
  typed/toset_test.go
  typed/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#16 Rename packages to sigs.k8s.io/structured-merge-diff
  fieldpath/element.go
  fieldpath/fromvalue.go
  fieldpath/fromvalue_test.go
  fieldpath/path.go
  fieldpath/path_test.go
  fieldpath/set_test.go
  go.mod
  go.sum
  typed/toset_test.go
  typed/typed.go
  typed/validate.go
  typed/validate_test.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#15 Refactoring for reusability
  typed/helpers.go
  typed/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#17 Implement merge and diff
  typed/helpers.go
  typed/merge.go
  typed/merge_test.go
  typed/symdiff_test.go
  typed/typed.go
  typed/validate.go
  value/unstructured.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#18 Fix Set.Difference: parent removal affects children
  fieldpath/set.go
  fieldpath/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#12 Rework test suite/framework to allow a sequence of actions
  tests/examples/example_test.go
  tests/framework/conflicts.go
  tests/framework/conflicts_test.go
  tests/framework/impl.go
  tests/framework/state.go
  tests/framework/state_test.go
  testvectors/all_test.go
  testvectors/listordering.go
  testvectors/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#19 Add SchemaSchema, validate all schemas
  schema/elements.go
  schema/schemaschema.go
  typed/helpers.go
  typed/merge_test.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#23 Create YAML Parser with Schema validation
  tests/examples/example_test.go
  tests/framework/impl.go
  tests/framework/state.go
  tests/framework/state_test.go
  typed/merge_test.go
  typed/parser.go
  typed/symdiff_test.go
  typed/toset_test.go
  typed/typed.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#25 Create signature for Updater
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 Signigicant changes to the test framework
  merge/update.go
  tests/examples/example_test.go
  tests/framework/conflicts.go
  tests/framework/conflicts_test.go
  tests/framework/impl.go
  tests/framework/state.go
  tests/framework/state_test.go
  typed/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 Start a command line tool
  smd/main.go
  smd/main_test.go
  smd/testdata/bad-schema.yaml
  smd/testdata/schema.yaml
  typed/helpers.go
  typed/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#29 Preparation for Updater code
  merge/conflict.go
  merge/conflict_test.go
  tests/framework/state.go
  typed/symdiff_test.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#32 Add update code
  merge/update.go
  merge/update_test.go
  tests/examples/example_test.go
  tests/framework/state.go
  typed/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 update readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 Move Owners logic to its file, add Difference
  merge/owners.go
  merge/owners_test.go
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 Add tests for leaf fields
  merge/leaf_test.go
  merge/update.go
  merge/update_test.go
  smd/internal/operation.go
  smd/testdata/scalar-compare-output.txt
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#39 Slight improvement (?) to Parser
  merge/update_test.go
  smd/internal/operation.go
  typed/merge_test.go
  typed/parser.go
  typed/symdiff_test.go
  typed/toset_test.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#38 update godoc for schema
  schema/doc.go
  schema/elements.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 Fix "HumanReadable" function name.
  fieldpath/element.go
  fieldpath/fromvalue.go
  typed/helpers.go
  typed/merge.go
  typed/merge_test.go
  typed/symdiff_test.go
  typed/typed.go
  value/unstructured.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 Add missing documentation files
  fieldpath/doc.go
  typed/doc.go
  value/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#42 s/owner/manager/g
  fieldpath/managers.go
  fieldpath/managers_test.go
  merge/conflict.go
  merge/conflict_test.go
  merge/leaf_test.go
  merge/update.go
  merge/update_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#37 Write tests for "sets"
  merge/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#43 Create State with ParseableType
  merge/leaf_test.go
  merge/set_test.go
  merge/update_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 Tests as lists
  merge/leaf_test.go
  merge/set_test.go
  merge/update_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
