Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2018-11, with the labels that each got.

#45 Make tests more readable
  merge/leaf_test.go
  merge/set_test.go
  merge/update_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#46 Move State to fixture package
  internal/cli/main_test.go
  internal/cli/operation.go
  internal/cli/options.go
  internal/fixture/state.go
  internal/fixture/state_test.go
  internal/testdata/bad-scalar.yaml
  internal/testdata/bad-schema.yaml
  internal/testdata/k8s-deployment.yaml
  internal/testdata/k8s-schema.yaml
  internal/testdata/list.yaml
  internal/testdata/scalar-compare-output.txt
  internal/testdata/scalar.yaml
  internal/testdata/schema.yaml
  internal/testdata/struct.yaml
  merge/leaf_test.go
  merge/set_test.go
  smd/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#47 space indented yaml should pass through untouched
  internal/fixture/state.go
  internal/fixture/state_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#48 Fix capture bug
  fieldpath/fromvalue.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 Export iterator for SetNodeMap
  fieldpath/set.go
  fieldpath/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 ToUnstructured shouldn't return internal types
  value/unstructured.go
  value/unstructured_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Add FromJSON and ToJSON methods for Value
  value/unstructured.go
  value/unstructured_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#52 Use json Unmarshaler rather than yaml
  value/unstructured.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
