Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-04, with the labels that each got.

#75 Run gofmt
  internal/fixture/state.go
  merge/key_test.go
  merge/multiple_appliers_test.go
  merge/nested_test.go
  merge/update.go
  typed/merge.go
  typed/toset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#73 Support atoms with multiple types
  merge/multiple_appliers_test.go
  schema/elements.go
  schema/elements_test.go
  schema/fromvalue.go
  schema/fromvalue_test.go
  typed/helpers.go
  typed/merge.go
  typed/merge_test.go
  typed/parser.go
  typed/remove.go
  typed/symdiff_test.go
  typed/toset_test.go
  typed/validate.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#77 Run gofmt -s
  merge/update.go
  typed/remove.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Update schema to support oneOf, and normalize objects
  schema/elements.go
  schema/schemaschema.go
  typed/typed.go
  typed/union.go
  typed/union_test.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#78 Integrate union in Apply/Update path
  internal/fixture/state.go
  merge/union_test.go
  merge/update.go
  typed/typed.go
  typed/union.go
  typed/union_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#80 Oneof lists
  merge/union_test.go
  schema/elements.go
  schema/schemaschema.go
  typed/typed.go
  typed/union.go
  typed/union_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
