Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-01, with the labels that each got.

#54 skip converting to same version
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#55 Remove empty sets from managers
  internal/fixture/state.go
  merge/leaf_test.go
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 generate schema from value function (for crds)
  schema/fromvalue.go
  schema/fromvalue_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 Fix test formatting from #56
  schema/fromvalue_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#59 Merge multiple types
  fieldpath/path.go
  internal/fixture/state.go
  merge/deduced_test.go
  merge/update.go
  typed/deduced.go
  typed/deduced_test.go
  typed/parser.go
  typed/typed.go
  typed/validate.go
  value/unstructured.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#60 Remove removed items from maps and lists on apply
  fieldpath/set.go
  merge/set_test.go
  merge/update.go
  typed/deduced.go
  typed/remove.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#61 Allow null scalars in validation
  typed/helpers.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#62 Don't try to convert to empty version
  internal/fixture/state.go
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
