Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-07, with the labels that each got.

#87 Add benchmarks for merge package
  merge/deduced_test.go
  merge/leaf_test.go
  merge/multiple_appliers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#88 Optimize benchmarks; permit serialization
  fieldpath/element.go
  fieldpath/element_test.go
  fieldpath/fromvalue.go
  fieldpath/path.go
  fieldpath/path_test.go
  fieldpath/set.go
  fieldpath/set_test.go
  internal/fixture/state.go
  merge/conflict.go
  merge/deduced_test.go
  merge/leaf_test.go
  merge/multiple_appliers_test.go
  typed/helpers.go
  value/less_test.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#89 use the technically-correct copy()
  fieldpath/element.go
  fieldpath/set.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#91 Unsafe
  fieldpath/serialize-pe.go
  fieldpath/serialize.go
Labels: approved, cncf-cla: yes, lgtm, size/L
