Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-02, with the labels that each got.

#63 Drop managed fields for obsolete versions
  internal/fixture/state.go
  merge/obsolete_versions_test.go
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#64 Add a few cross-version tests
  merge/leaf_test.go
  merge/set_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 FixTabsOrDie doesn't work well with YAML structs
  internal/fixture/state.go
  internal/fixture/state_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#65 Fix bug with removing non leaf items
  fieldpath/set.go
  merge/key_test.go
  merge/nested_test.go
  merge/update.go
  typed/deduced.go
  typed/remove.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#69 Add broken tests for multiple appliers
  merge/multiple_appliers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Add nested test for deduced types
  merge/deduced_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#67 Fix bogus conflicts comparison and reporting
  internal/fixture/state.go
Labels: approved, cncf-cla: yes, lgtm, size/M
