Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-08, with the labels that each got.

#93 improved memory management
  typed/helpers.go
  typed/merge.go
  typed/validate.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#94 Use index rather than pointer in Map.Set/Get
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#95 reflect.DeepEqual, not even once
  schema/elements_test.go
  schema/equals.go
  schema/equals_test.go
  typed/merge.go
  typed/typed.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#96 disable unions, since they're still experimental
  internal/fixture/state.go
  merge/union_test.go
  merge/update.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#97 memory pools for walkers
  typed/typed.go
  typed/validate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#98 disable one more union bit
  merge/update.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Remove merge from Compare
  internal/testdata/scalar-compare-output.txt
  typed/deduced_test.go
  typed/symdiff_test.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/S
