Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2019-11, with the labels that each got.

#124 Perf/add crd example
  internal/cli/main_test.go
  internal/testdata/k8s-schema.yaml
  internal/testdata/podset.json
  internal/testdata/prometheus-crd.yaml
  internal/testdata/prometheus-crdset.json
  merge/real_test.go
  typed/parser_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#125 Add additional benchmarks for "updates"
  merge/real_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#126 Implement equality for Values
  value/less_test.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#120 Fix wg-apply mailing list link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Cherrypick #126 to 1.0 - Implement equality for Values
  value/less_test.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#127 typed: Round-trip to/from unstructured in benchmark
  typed/parser_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
