Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2020-05, with the labels that each got.

#162 Add Conflicts.ToSet()
  merge/conflict.go
  merge/conflict_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#161 Add ignored fields to update
  fieldpath/set.go
  fieldpath/set_test.go
  go.mod
  go.sum
  internal/fixture/state.go
  merge/ignore_test.go
  merge/update.go
  typed/comparison_test.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL, wg/api-expression

#165 Link to wg-api-expression slack and mailing-list
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
