Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2020-02, with the labels that each got.

#137 Use Compare when serializing rather than Less
  fieldpath/serialize.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#153 Optimize TypedValue.Compare for value reflector
  fieldpath/fromvalue.go
  typed/helpers.go
  typed/merge.go
  typed/remove.go
  typed/tofieldset.go
  typed/validate.go
  value/list.go
  value/listreflect.go
  value/listunstructured.go
  value/map.go
  value/mapreflect.go
  value/mapunstructured.go
  value/reflectcache.go
  value/structreflect.go
  value/value.go
  value/valuereflect.go
  value/valuereflect_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL

#155 Use freelists instead of sync.Pool for value object recycling
  fieldpath/fromvalue.go
  typed/helpers.go
  typed/merge.go
  typed/remove.go
  typed/tofieldset.go
  typed/typed.go
  typed/validate.go
  value/allocator.go
  value/list.go
  value/listreflect.go
  value/listunstructured.go
  value/map.go
  value/mapreflect.go
  value/mapunstructured.go
  value/reflectcache.go
  value/structreflect.go
  value/value.go
  value/valuereflect.go
  value/valuereflect_test.go
  value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL

#156 Convert numbers like Kubernetes does for json.Marshaler types
  value/reflectcache.go
  value/reflectcache_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
