Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2020-01, with the labels that each got.

#142 rename value conversion methods
  fieldpath/fromvalue.go
  typed/helpers.go
  typed/remove.go
  typed/union.go
  value/value.go
  value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#144 Back-port Fix from Jenny for ugly errors to 2.0
  typed/helpers.go
  typed/symdiff_test.go
  typed/validate.go
  typed/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 make schema.Equals pointer receivers for Map and Schema
  schema/elements_test.go
  schema/equals.go
  schema/equals_test.go
  typed/merge.go
  typed/typed.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#148 Run non-required union tests last
  internal/fixture/state.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#149 value.Equals should check types in both directions
  value/less_test.go
  value/value.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#146 Allow tests to specify objects in different versions
  internal/fixture/state.go
  merge/deduced_test.go
  merge/key_test.go
  merge/leaf_test.go
  merge/multiple_appliers_test.go
  merge/nested_test.go
  merge/obsolete_versions_test.go
  merge/preserve_unknown_test.go
  merge/real_test.go
  merge/set_test.go
  merge/union_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#150 Re-introduce benchmark test for Updates in different versions
  merge/real_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#136 Add reflector based implementation of value interface
  .gitignore
  typed/merge.go
  typed/parser.go
  typed/union.go
  typed/validate_test.go
  value/fields.go
  value/jsontagutil.go
  value/listreflect.go
  value/map.go
  value/mapreflect.go
  value/mapunstructured.go
  value/structreflect.go
  value/valuereflect.go
  value/valuereflect_test.go
  value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#145 Make fieldset v1 serialization alphabetical
  fieldpath/serialize.go
  internal/cli/main_test.go
  internal/testdata/endpointsset.json
  internal/testdata/nodeset.json
  internal/testdata/podset.json
  internal/testdata/prometheus-crdset.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#151 Optimize sync.Pool usage and value.Equals implementations
  fieldpath/fromvalue.go
  typed/remove.go
  value/list.go
  value/listreflect.go
  value/listunstructured.go
  value/map.go
  value/mapreflect.go
  value/mapunstructured.go
  value/structreflect.go
  value/value.go
  value/valuereflect.go
  value/valuereflect_test.go
  value/valueunstructured.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#119 fix golint errors
  fieldpath/serialize.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, needs-ok-to-test, size/S

#152 Optimize conversion to unstructured
  value/fields.go
  value/listreflect.go
  value/mapreflect.go
  value/reflectcache.go
  value/structreflect.go
  value/valuereflect.go
  value/valuereflect_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL
