Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2023-07, with the labels that each got.

#237 Do not use Compare for Equality checks
  go.mod
  go.sum
  internal/fixture/state.go
  merge/obsolete_versions_test.go
  merge/real_test.go
  merge/set_test.go
  merge/update.go
Labels: cncf-cla: yes, approved, lgtm, size/L

#243 lavalamp and jennybuckley are emeritus now
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#242 deep copy slice object during append
  merge/conflict.go
  merge/conflict_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test
