Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2023-03, with the labels that each got.

#233 Minor cleanups
  merge/nested_test.go
  schema/elements.go
  schema/elements_test.go
  schema/schemaschema.go
  typed/merge.go
  typed/typed.go
  typed/validate.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#232 Replace k8s.gcr.io with registry.k8s.io
  internal/testdata/k8s-deployment.yaml
  internal/testdata/node.yaml
Labels: cncf-cla: yes, kind/cleanup, approved, size/M, lgtm

#231 Check inlined struct field's kind before recursively calling value.buildStructCacheEntry
  value/reflectcache.go
  value/reflectcache_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm, ok-to-test
