Repository kubernetes-sigs/structured-merge-diff, pull requests merged in 2025-03, with the labels that each got.

#283 Switch from gofuzz to randfill
  go.mod
  go.sum
  schema/equals_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#282 fix: update error formatting and test naming
  fieldpath/managers_test.go
  internal/cli/operation.go
  typed/validate.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#285 Add yongruilin to reviewers for SMD
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm
